### ISSUE TITLE
ojet build fails with dependency issues

### ISSUE THREAD

**Issue by pransen** [oracle/ojet-cli#4] opened 2018-09-21 14:24 UTC
Stack: 

Error: node_modules/jquery/package.json: ENOENT: no such file or directory, open 'node_modules/jquery/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.readFileSync (/scratch/pransen/HybridApps/MLMobileApp/node_modules/@oracle/oraclejet-tooling/node_modules/fs-extra/node_modules/jsonfile/index.js:61:22)
    at _getVersionFromNpm (/scratch/pransen/HybridApps/MLMobileApp/node_modules/@oracle/oraclejet-tooling/lib/util.js:1033:26)
    at Object.util.deleteDir.util.deleteFile.util.exec.child.stdout.on.child.stderr.on.util.spawn.task.stdout.on.task.stderr.on.util.log.util.validateType.util.getValidArraySize.util.fsExists.util.fsExistsSync.util.hasWhiteSpace.util.getDirectories.util.getFileList.util.getDirectories.util.getFiles.file.src.forEach.util.getPathComponents.util.getRequestedComponentVersion.util.getPlainComponentName.util.mergeDefaultOptions.util.mergePlatformOptions.util.getAllThemes.util.checkForHttpErrors.platforms.filter.util.printList.itemsByFolder.forEach.util.request.util.getLibVersionsObj (/scratch/pransen/HybridApps/MLMobileApp/node_modules/@oracle/oraclejet-tooling/lib/util.js:1023:13)
    at Object.<anonymous> (/scratch/pransen/HybridApps/MLMobileApp/node_modules/@oracle/oraclejet-tooling/lib/npmCopy.js:24:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by pransen** [comment] 2018-09-21 14:41
Version 5.2.0

**Comment by peppertech** [comment] 2019-03-13 21:23
Closing as Duplicate of Issue #2

**Closed as completed by peppertech** 2019-03-13 21:23 UTC
